package com.genai.ollamarestapi.export.excel;

import com.genai.ollamarestapi.export.common.ReportContext;
import com.genai.ollamarestapi.export.common.ReportStatistics;
import org.apache.poi.ss.usermodel.*;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

public class ExcelSummaryBuilder {

    private ExcelSummaryBuilder() {
    }

    public static void create(

        Workbook workbook,

        Sheet sheet,

        ExcelStyleFactory styles,

        ReportContext context,

        int startRow) {

        ReportStatistics stats = context.getStatistics();

        startRow += 2;

        createTitle(sheet, styles, startRow++);

        createRow(sheet, styles, startRow++,
                "Story Key", context.getMetadata().getStoryKey());

        createRow(sheet, styles, startRow++,
                "Generated Test Cases",
                String.valueOf(stats.getTotal()));

        createRow(sheet, styles, startRow++,
                "High Priority",
                String.valueOf(stats.getHigh()));

        createRow(sheet, styles, startRow++,
                "Medium Priority",
                String.valueOf(stats.getMedium()));

        createRow(sheet, styles, startRow++,
                "Low Priority",
                String.valueOf(stats.getLow()));

        createRow(sheet, styles, startRow++,
                "Generated By",
                "TestPilot AI Enterprise");

        createRow(sheet, styles, startRow++,
                "Generated On",
                LocalDateTime.now().format(
                        DateTimeFormatter.ofPattern(
                                "dd-MMM-yyyy hh:mm a")));

    }

    private static void createTitle(

            Sheet sheet,

            ExcelStyleFactory styles,

            int rowNumber) {

        Row row = sheet.createRow(rowNumber);

        Cell cell = row.createCell(0);

        cell.setCellValue("REPORT SUMMARY");

        cell.setCellStyle(
                styles.getSummaryTitleStyle());

    }

    private static void createRow(

            Sheet sheet,

            ExcelStyleFactory styles,

            int rowNumber,

            String label,

            String value) {

        Row row = sheet.createRow(rowNumber);

        Cell c1 = row.createCell(0);
        c1.setCellValue(label);
        c1.setCellStyle(styles.getSummaryLabelStyle());

        Cell c2 = row.createCell(1);
        c2.setCellValue(value);
        c2.setCellStyle(styles.getSummaryValueStyle());

    }

}