package com.genai.ollamarestapi.export.excel;

import org.apache.poi.common.usermodel.HyperlinkType;
import org.apache.poi.ss.usermodel.*;
import org.apache.poi.ss.util.CellRangeAddress;

import com.genai.ollamarestapi.export.common.ReportContext;

import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

public class ExcelHeaderBuilder {

    private ExcelHeaderBuilder() {
    }

    public static int build(

        Sheet sheet,

        ExcelStyleFactory styles,

        ReportContext context) {

        Workbook workbook = sheet.getWorkbook();

        //------------------------------------------
        // Row 0
        //------------------------------------------

        Row titleRow = sheet.createRow(0);

        titleRow.setHeightInPoints(30);

        Cell title = titleRow.createCell(0);

        title.setCellValue(
                ExcelConstants.REPORT_TITLE);

        title.setCellStyle(
                styles.getTitleStyle());

        sheet.addMergedRegion(

                new CellRangeAddress(

                        0,

                        0,

                        0,

                        7

                )

        );

        //------------------------------------------
        // Row 1
        //------------------------------------------

        Row versionRow = sheet.createRow(1);

        Cell version = versionRow.createCell(0);

        version.setCellValue(

                ExcelConstants.VERSION

        );

        Font versionFont =
                workbook.createFont();

        versionFont.setItalic(true);

        CellStyle versionStyle =
                workbook.createCellStyle();

        versionStyle.setFont(versionFont);

        version.setCellStyle(versionStyle);

        sheet.addMergedRegion(

                new CellRangeAddress(

                        1,

                        1,

                        0,

                        7

                )

        );

        //------------------------------------------
        // Row 3
        //------------------------------------------

        Row infoRow1 =
                sheet.createRow(3);

        infoRow1.createCell(0)
                .setCellValue("Story Key");

        infoRow1.createCell(1)
        .setCellValue(
                context.getMetadata()
                        .getStoryKey());

        infoRow1.createCell(3)
                .setCellValue("Generated");

        infoRow1.createCell(4)
                .setCellValue(

                        LocalDateTime.now()

                                .format(

                                        DateTimeFormatter.ofPattern(

                                                "dd-MMM-yyyy HH:mm:ss"

                                        )

                                )

                );

        //------------------------------------------
        // Row 4
        //------------------------------------------

        Row infoRow2 =
                sheet.createRow(4);

        infoRow2.createCell(0)
                .setCellValue("Generated By");

        infoRow2.createCell(1)
        .setCellValue(
                context.getMetadata()
                        .getGeneratedBy());

        infoRow2.createCell(3)
                .setCellValue("Total Test Cases");

        infoRow2.createCell(4)
        .setCellValue(
                context.getStatistics()
                        .getTotal());

        //------------------------------------------
        // Row 5
        //------------------------------------------

        Row infoRow3 =
                sheet.createRow(5);

        infoRow3.createCell(0)
                .setCellValue("Website");

        CreationHelper helper =
                workbook.getCreationHelper();

        Hyperlink hyperlink =
                helper.createHyperlink(

                        HyperlinkType.URL);

        hyperlink.setAddress(

                ExcelConstants.WEBSITE);

        Cell website =
                infoRow3.createCell(1);

        website.setCellValue(

                ExcelConstants.WEBSITE);

        website.setHyperlink(hyperlink);

        CellStyle linkStyle =
                workbook.createCellStyle();

        Font linkFont =
                workbook.createFont();

        linkFont.setUnderline(

                Font.U_SINGLE);

        linkFont.setColor(

                IndexedColors.BLUE.getIndex());

        linkStyle.setFont(linkFont);

        website.setCellStyle(linkStyle);

        //------------------------------------------
        // Blank Row
        //------------------------------------------

        sheet.createRow(6);

        //------------------------------------------
        // Return header row index
        //------------------------------------------

        return 7;

    }

}