spring.application.name=ollamarestapi
spring.ai.ollama.chat.model=mistral

#jira.username=email@domain.com
#jira.apiToken=eh2fl8Nl79LSQaN4qlHU0ixc2gXNfdCNI_9XpWuw=D6B56B5C
#jira.apiUrl=https://jiraprojecturl.atlassian.net

jira.username=email@gmail.com
jira.apiToken=
jira.apiUrl=https://project.atlassian.net

ollama.url=http://localhost:11434
ollama.model=mistral



