spring.application.name=ollamarestapi
spring.ai.ollama.chat.model=mistral


jira.username=email@gmail.com
jira.apiToken=
jira.apiUrl=https://project.atlassian.net

ollama.url=http://localhost:11434
ollama.model=mistral



