package com.genai.ollamarestapi.export.word;

public final class WordConstants {

    private WordConstants() {
    }

    public static final String COMPANY_NAME = "TestPilot AI";

    public static final String PRODUCT = "Enterprise AI Test Case Generator";

    public static final String VERSION = "Enterprise Edition v1.0";

    public static final String GENERATED_BY = "Generated by TestPilot AI Enterprise";

    public static final String REPORT_TITLE = "AI GENERATED TEST CASE REPORT";

    public static final String JIRA_BROWSE_URL = "https://genaiauto.atlassian.net/browse/";
}