package com.genai.ollamarestapi.export.word;

import com.genai.ollamarestapi.export.common.ReportContext;
import com.genai.ollamarestapi.model.ai.TestCase;
import org.apache.poi.xwpf.usermodel.*;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.List;

public final class WordHeader {

    private WordHeader() {
    }

    public static void create(
        XWPFDocument document,
        ReportContext context) throws Exception {

        // ----------------------------------------------------
        // Company Logo
        // ----------------------------------------------------

        XWPFParagraph headerParagraph = document.createParagraph();

        WordLogoUtil.addLogo(

                document,

                headerParagraph,

                "/logo.png");

        // ----------------------------------------------------
        // Report Title
        // ----------------------------------------------------

        XWPFParagraph title = document.createParagraph();

        title.setAlignment(
                ParagraphAlignment.CENTER);

        XWPFRun titleRun = title.createRun();

        WordStyles.title(titleRun);

        titleRun.setText(
                WordConstants.REPORT_TITLE);

        // ----------------------------------------------------
        // Subtitle
        // ----------------------------------------------------

        XWPFParagraph subtitle = document.createParagraph();

        subtitle.setAlignment(
                ParagraphAlignment.CENTER);

        XWPFRun subtitleRun = subtitle.createRun();

        WordStyles.normal(subtitleRun);

        subtitleRun.setText(
                WordConstants.PRODUCT);

        // ----------------------------------------------------
        // Version
        // ----------------------------------------------------

        XWPFParagraph version = document.createParagraph();

        version.setAlignment(
                ParagraphAlignment.CENTER);

        XWPFRun versionRun = version.createRun();

        versionRun.setItalic(true);

        versionRun.setFontSize(11);

        versionRun.setText(
                WordConstants.VERSION);

        // ----------------------------------------------------
        // Blank Line
        // ----------------------------------------------------

        document.createParagraph();

        // ----------------------------------------------------
        // Information Table
        // ----------------------------------------------------

        XWPFTable table = document.createTable(6, 2);

        table.setWidth("100%");

        // ---------------------------------------
        // Story Key
        // ---------------------------------------

        addLabel(table, 0, 0, "Story Key");

        addValue(
                table,
                0,
                1,
                context.getMetadata().getStoryKey());

        // ---------------------------------------
        // Jira URL
        // ---------------------------------------

        addLabel(table, 1, 0, "Jira URL");

        addValue(
                table,
                2,
                1,
                WordConstants.JIRA_BROWSE_URL + context.getMetadata().getStoryKey());

        addLabel(table, 2, 0, "Generated");

        addValue(

                table,

                1,

                1,

                LocalDateTime.now()

                        .format(

                                DateTimeFormatter.ofPattern(

                                        "dd-MMM-yyyy HH:mm:ss"

                                )

                        )

        );

        addLabel(table, 3, 0, "Generated By");

        addValue(

                table,

                3,

                1,

                WordConstants.GENERATED_BY

        );

        addLabel(table, 4, 0, "Total Test Cases");

        addValue(

                table,

                4,

                1,

                String.valueOf(context.getStatistics().getTotal())

        );

        addLabel(table, 5, 0, "Report");

        addValue(

                table,

                5,

                1,

                "Enterprise AI Test Case Report"

        );

        // ----------------------------------------------------
        // Executive Summary
        // ----------------------------------------------------

        document.createParagraph();

        XWPFParagraph summaryTitle = document.createParagraph();

        XWPFRun run = summaryTitle.createRun();

        WordStyles.heading(run);

        run.setText(
                "Executive Summary");

        XWPFParagraph summary = document.createParagraph();

        XWPFRun sr = summary.createRun();

        WordStyles.normal(sr);

        sr.setText(

                "This report contains AI-generated test cases " +

                        "created by TestPilot AI Enterprise based on " +

                        "Jira Story " +

                        context.getMetadata().getStoryKey() +

                        ". The report includes functional validation, " +

                        "priority classification, execution steps, " +

                        "expected results, and summary statistics."

        );

        document.createParagraph();

    }

    // --------------------------------------------------------
    // Add Logo
    // --------------------------------------------------------

    /*
     * private static void addLogo(
     * 
     * XWPFDocument document)
     * 
     * throws Exception {
     * 
     * InputStream stream =
     * 
     * WordHeader.class
     * 
     * .getResourceAsStream(
     * 
     * "/logo.png"
     * 
     * );
     * 
     * if(stream==null){
     * 
     * return;
     * 
     * }
     * 
     * XWPFParagraph paragraph =
     * 
     * document.createParagraph();
     * 
     * paragraph.setAlignment(
     * 
     * ParagraphAlignment.CENTER);
     * 
     * XWPFRun run =
     * 
     * paragraph.createRun();
     * 
     * run.addPicture(
     * 
     * stream,
     * 
     * Document.PICTURE_TYPE_PNG,
     * 
     * "logo.png",
     * 
     * Units.toEMU(120),
     * 
     * Units.toEMU(120)
     * 
     * );
     * 
     * stream.close();
     * 
     * }
     */

    // --------------------------------------------------------
    // Labels
    // --------------------------------------------------------

    private static void addLabel(

            XWPFTable table,

            int row,

            int column,

            String value) {

        XWPFRun run =

                table

                        .getRow(row)

                        .getCell(column)

                        .getParagraphs()

                        .get(0)

                        .createRun();

        WordStyles.heading(run);

        run.setText(value);

    }

    // --------------------------------------------------------
    // Values
    // --------------------------------------------------------

    private static void addValue(

            XWPFTable table,

            int row,

            int column,

            String value) {

        XWPFRun run =

                table

                        .getRow(row)

                        .getCell(column)

                        .getParagraphs()

                        .get(0)

                        .createRun();

        WordStyles.normal(run);

        run.setText(value);

    }

}