package com.genai.ollamarestapi.export.pdf;

import com.lowagie.text.*;
import com.lowagie.text.pdf.*;

import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

public class PdfPageEvent extends PdfPageEventHelper {

    @Override
    public void onEndPage(
            PdfWriter writer,
            Document document) {

        PdfContentByte canvas =
                writer.getDirectContent();

        Font headerFont =
                FontFactory.getFont(
                        FontFactory.HELVETICA_BOLD,
                        10);

        Font footerFont =
                FontFactory.getFont(
                        FontFactory.HELVETICA,
                        8);

        //-----------------------------
        // HEADER
        //-----------------------------

        ColumnText.showTextAligned(

                canvas,

                Element.ALIGN_LEFT,

                new Phrase(
                        "TestPilot AI Enterprise",
                        headerFont),

                document.left(),

                document.top()+20,

                0);

        //-----------------------------
        // FOOTER LEFT
        //-----------------------------

        ColumnText.showTextAligned(

                canvas,

                Element.ALIGN_LEFT,

                new Phrase(

                        "Generated : "

                        + LocalDateTime.now()

                        .format(

                                DateTimeFormatter.ofPattern(

                                        "dd-MMM-yyyy HH:mm")),

                        footerFont),

                document.left(),

                document.bottom()-20,

                0);

        //-----------------------------
        // FOOTER CENTER
        //-----------------------------

        ColumnText.showTextAligned(

                canvas,

                Element.ALIGN_CENTER,

                new Phrase(

                        "Generated by TestPilot AI",

                        footerFont),

                (document.left()+document.right())/2,

                document.bottom()-20,

                0);

        //-----------------------------
        // FOOTER RIGHT
        //-----------------------------

        ColumnText.showTextAligned(

                canvas,

                Element.ALIGN_RIGHT,

                new Phrase(

                        "Page "

                        + writer.getPageNumber(),

                        footerFont),

                document.right(),

                document.bottom()-20,

                0);

    }

}