package com.genai.ollamarestapi.export.pdf;

import com.genai.ollamarestapi.export.common.ReportContext;
import com.genai.ollamarestapi.export.common.ReportStatistics;
import com.lowagie.text.*;
import com.lowagie.text.pdf.PdfPCell;
import com.lowagie.text.pdf.PdfPTable;
import java.awt.Color;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

public final class PdfSummaryBuilder {

    private PdfSummaryBuilder() {
    }

    public static void build(
        Document document,
        ReportContext context) throws Exception {

        document.newPage();

        Paragraph title = new Paragraph(

                "REPORT SUMMARY",

                PdfStyles.SECTION);

        title.setSpacingAfter(20);

        document.add(title);
        
        ReportStatistics stats = context.getStatistics();
        /* int high = 0;
        int medium = 0;
        int low = 0;

        int ui = 0;
        int api = 0;
        int selenium = 0;

        for (TestCase tc : testCases) {

            if (tc.getPriority() != null) {

                switch (tc.getPriority().toUpperCase()) {

                    case "HIGH":
                        high++;
                        break;

                    case "MEDIUM":
                        medium++;
                        break;

                    case "LOW":
                        low++;
                        break;

                }

            }

            if (tc.getType() != null) {

                String type = tc.getType().toUpperCase();

                if (type.contains("UI"))
                    ui++;

                else if (type.contains("API"))
                    api++;

                else if (type.contains("SELENIUM"))
                    selenium++;

            }

        } */

        PdfPTable table = new PdfPTable(2);

        table.setWidthPercentage(100);

        table.setWidths(new float[]{35,65});

        addRow(table,"Story Key", context.getMetadata().getStoryKey());

        addRow(table,"Generated By", context.getMetadata().getGeneratedBy());

        addRow(

                table,

                "Generated On",

                LocalDateTime.now()

                        .format(

                                DateTimeFormatter.ofPattern(

                                        "dd-MMM-yyyy HH:mm")));

        addRow(

                table,

                "Total Test Cases",

                String.valueOf(stats.getTotal()));

        addRow(

                table,

                "High Priority",

                String.valueOf(stats.getHigh()));

        addRow(

                table,

                "Medium Priority",

                String.valueOf(stats.getMedium()));

        addRow(

                table,

                "Low Priority",

                String.valueOf(stats.getLow()));

        addRow(

                table,

                "UI Test Cases",

                String.valueOf(stats.getUi()));

        addRow(

                table,

                "API Test Cases",

                String.valueOf(stats.getApi()));

        addRow(

                table,

                "Selenium Scripts",

                String.valueOf(stats.getSelenium()));

        document.add(table);

    }

    //------------------------------------------------

    private static void addRow(

            PdfPTable table,

            String label,

            String value) {

        PdfPCell left = new PdfPCell(

                new Phrase(

                        label,

                        PdfStyles.BOLD));

        left.setBackgroundColor(

                new Color(230,230,230));

        left.setPadding(8);

        table.addCell(left);

        PdfPCell right = new PdfPCell(

                new Phrase(

                        value,

                        PdfStyles.NORMAL));

        right.setPadding(8);

        table.addCell(right);

    }

}