package com.genai.ollamarestapi.export;

import com.genai.ollamarestapi.model.ai.TestCase;
import org.apache.poi.ss.usermodel.*;

import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.List;

public class ExcelSummaryBuilder {

    private ExcelSummaryBuilder() {
    }

    public static void create(

            Workbook workbook,

            Sheet sheet,

            ExcelStyleFactory styles,

            String storyKey,

            List<TestCase> testCases,

            int startRow) {

        int high = 0;
        int medium = 0;
        int low = 0;

        for (TestCase tc : testCases) {

            if (tc.getPriority() == null)
                continue;

            switch (tc.getPriority().toUpperCase()) {

                case "HIGH":
                    high++;
                    break;

                case "MEDIUM":
                    medium++;
                    break;

                case "LOW":
                    low++;
                    break;

            }

        }

        startRow += 2;

        createTitle(sheet, styles, startRow++);

        createRow(sheet, styles, startRow++,
                "Story Key", storyKey);

        createRow(sheet, styles, startRow++,
                "Generated Test Cases",
                String.valueOf(testCases.size()));

        createRow(sheet, styles, startRow++,
                "High Priority",
                String.valueOf(high));

        createRow(sheet, styles, startRow++,
                "Medium Priority",
                String.valueOf(medium));

        createRow(sheet, styles, startRow++,
                "Low Priority",
                String.valueOf(low));

        createRow(sheet, styles, startRow++,
                "Generated By",
                "TestPilot AI Enterprise");

        createRow(sheet, styles, startRow++,
                "Generated On",
                LocalDateTime.now().format(
                        DateTimeFormatter.ofPattern(
                                "dd-MMM-yyyy hh:mm a")));

    }

    private static void createTitle(

            Sheet sheet,

            ExcelStyleFactory styles,

            int rowNumber) {

        Row row = sheet.createRow(rowNumber);

        Cell cell = row.createCell(0);

        cell.setCellValue("REPORT SUMMARY");

        cell.setCellStyle(
                styles.getSummaryTitleStyle());

    }

    private static void createRow(

            Sheet sheet,

            ExcelStyleFactory styles,

            int rowNumber,

            String label,

            String value) {

        Row row = sheet.createRow(rowNumber);

        Cell c1 = row.createCell(0);
        c1.setCellValue(label);
        c1.setCellStyle(styles.getSummaryLabelStyle());

        Cell c2 = row.createCell(1);
        c2.setCellValue(value);
        c2.setCellStyle(styles.getSummaryValueStyle());

    }

}