package com.genai.ollamarestapi.export;

public final class ExcelConstants {

    private ExcelConstants() {
    }

    public static final String SHEET_NAME = "AI Test Cases";

    public static final String REPORT_TITLE = "TestPilot AI Enterprise Test Case Report";

    public static final String COMPANY = "TestPilot AI";

    public static final String AUTHOR = "TestPilot AI";

    public static final String SUBJECT = "AI Generated Test Cases";

    public static final String[] HEADERS = {

            "ID",
            "Title",
            "Description",
            "Priority",
            "Type",
            "Precondition",
            "Steps",
            "Expected Result"

    };

    public static final String VERSION = "Enterprise Edition v1.0";

    public static final String GENERATED_BY = "Generated by TestPilot AI";

    public static final String WEBSITE = "https://www.testpilotai.com";

}