package com.genai.ollamarestapi.export;

public final class PdfConstants {

    private PdfConstants() {}

    public static final String COMPANY =
            "TestPilot AI";

    public static final String PRODUCT =
            "AI Powered Jira Test Case Generator";

    public static final String VERSION =
            "Enterprise Edition";

    public static final String GENERATED_BY =
            "Generated by TestPilot AI";

}