package com.genai.ollamarestapi.export;

import com.genai.ollamarestapi.model.ai.TestCase;
import com.lowagie.text.*;
import com.lowagie.text.pdf.PdfPCell;
import com.lowagie.text.pdf.PdfPTable;
import java.awt.Color;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.List;

public final class PdfSummaryBuilder {

    private PdfSummaryBuilder() {
    }

    public static void build(

            Document document,

            String storyKey,

            List<TestCase> testCases)

            throws Exception {

        document.newPage();

        Paragraph title = new Paragraph(

                "REPORT SUMMARY",

                PdfStyles.SECTION);

        title.setSpacingAfter(20);

        document.add(title);

        int high = 0;
        int medium = 0;
        int low = 0;

        int ui = 0;
        int api = 0;
        int selenium = 0;

        for (TestCase tc : testCases) {

            if (tc.getPriority() != null) {

                switch (tc.getPriority().toUpperCase()) {

                    case "HIGH":
                        high++;
                        break;

                    case "MEDIUM":
                        medium++;
                        break;

                    case "LOW":
                        low++;
                        break;

                }

            }

            if (tc.getType() != null) {

                String type = tc.getType().toUpperCase();

                if (type.contains("UI"))
                    ui++;

                else if (type.contains("API"))
                    api++;

                else if (type.contains("SELENIUM"))
                    selenium++;

            }

        }

        PdfPTable table = new PdfPTable(2);

        table.setWidthPercentage(100);

        table.setWidths(new float[]{35,65});

        addRow(table,"Story Key",storyKey);

        addRow(table,"Generated By","TestPilot AI Enterprise");

        addRow(

                table,

                "Generated On",

                LocalDateTime.now()

                        .format(

                                DateTimeFormatter.ofPattern(

                                        "dd-MMM-yyyy HH:mm")));

        addRow(

                table,

                "Total Test Cases",

                String.valueOf(testCases.size()));

        addRow(

                table,

                "High Priority",

                String.valueOf(high));

        addRow(

                table,

                "Medium Priority",

                String.valueOf(medium));

        addRow(

                table,

                "Low Priority",

                String.valueOf(low));

        addRow(

                table,

                "UI Test Cases",

                String.valueOf(ui));

        addRow(

                table,

                "API Test Cases",

                String.valueOf(api));

        addRow(

                table,

                "Selenium Scripts",

                String.valueOf(selenium));

        document.add(table);

    }

    //------------------------------------------------

    private static void addRow(

            PdfPTable table,

            String label,

            String value) {

        PdfPCell left = new PdfPCell(

                new Phrase(

                        label,

                        PdfStyles.BOLD));

        left.setBackgroundColor(

                new Color(230,230,230));

        left.setPadding(8);

        table.addCell(left);

        PdfPCell right = new PdfPCell(

                new Phrase(

                        value,

                        PdfStyles.NORMAL));

        right.setPadding(8);

        table.addCell(right);

    }

}