package com.genai.ollamarestapi.export;

import org.apache.poi.xwpf.model.XWPFHeaderFooterPolicy;
import org.apache.poi.xwpf.usermodel.*;

public final class WordHeaderFooter {

    private WordHeaderFooter(){}

    public static void apply(

            XWPFDocument document,

            String storyKey){

        XWPFHeaderFooterPolicy policy =
                document.createHeaderFooterPolicy();

        //---------------- HEADER ----------------

        XWPFHeader header =
                policy.createHeader(
                        XWPFHeaderFooterPolicy.DEFAULT);

        XWPFParagraph hp =
                header.createParagraph();

        hp.setAlignment(
                ParagraphAlignment.CENTER);

        XWPFRun hr =
                hp.createRun();

        hr.setBold(true);

        hr.setFontSize(11);

        hr.setText(
                "TestPilot AI Enterprise | Story : "
                        + storyKey);

        //---------------- FOOTER ----------------

        XWPFFooter footer =
                policy.createFooter(
                        XWPFHeaderFooterPolicy.DEFAULT);

        XWPFParagraph fp =
                footer.createParagraph();

        fp.setAlignment(
                ParagraphAlignment.CENTER);

        XWPFRun fr =
                fp.createRun();

        fr.setItalic(true);

        fr.setFontSize(10);

        fr.setText(
                "Generated by TestPilot AI Enterprise");

    }

}